### PR TITLE
Added Source Dependencies via Submodules

### PR DESCRIPTION
**Pull request by ferria**
RE: #105.  Source (i.e. non-binary) dependencies have been added via Git Submodules.  Binary dependencies like boost's binaries and CUDA are not included at the moment, and a discussion of how to handle them is happening [here](https://github.com/Synodic-Software/Soul-Engine-Dependencies/issues/2).

### CODE REVIEW

**Comment by Behemyth** [comment]
I think it has been decided to leave Boost as a user dependency, as it will be dropped in the future.  Thanks for bringing it in!

**Comment by ferria** [comment]
The duplicated directories is a result of me creating a directory for each dependency and then adding the submodule to that subdirectory instead of adding them all directly to `Libraries/src/`.  Do you want me to change this?

**Comment by Behemyth** [comment]
That would be a good change!

**Comment by ferria** [comment]
@Behemyth done

**Pull request merged**
